### ISSUE TITLE
Model creation question

### ISSUE THREAD

**Issue by superfamousdog** [rajshah4/snowflake-notebooks#1]
Thanks for the great documentation! In sentence_transformers.ipynb, when you create the model from SentenceTransformers:

`model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2" )`

Did you ever come across the following error?

ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/all-MiniLM-L6-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff676667c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")

I'm running my notebook inside Snowflake. 

Also, your tip about "I used sentence transfomers version 2.2.2 and this didn't work with 2.7.0 when I ran it in May 2024." saved me.

**Comment by rajshah4** [comment]
Glad it was helpful!  For running inside Snowflake, you are probably get the default blocking for external connections. However, you can add external access very easily - https://docs.snowflake.com/en/user-guide/ui-snowsight/notebooks-external-access  Also, if you run notebooks on containers, you will get more flexibility for versions, since you aren't tied to the Snowflake package manager on the Snowflake warehouses.

**Comment by superfamousdog** [comment]
Thank you!
